name: catChecker

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 5
      matrix:
        python-version: [3.10.x]

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v3
        with:
          python-version: ${{ matrix.python-version }}
      - name: Update apt packages
        run: |
          sudo apt-get update
          sudo apt-get upgrade -y
      - name: Install dependencies
        run: |
          sudo apt-get install libpq-dev libxml2-dev libxslt-dev python3-dev
          python3 -m pip install --upgrade pip
          pip3 install wheel flake8 flake8-print flake8-quotes
          pip3 install -r requirements.txt
      - name: Check for showstoppers
        run: |
          # stop the build if there are Python syntax errors
          flake8 . --count --select=E999 --show-source --statistics
